# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b248e3f2f904bb9f081b555345a6fe809f2d6d4d57fa33f29ecb49ac9dcbd8c32387a2d18814a84de70a51775a3078823452e41a8f6982213208dca8166ed2a

test:
  secret_key_base: 019e3c662dc42fde7c80ac8a020b11eae74f539f1f338fd8795bfcb57469282aeeb6dfade9d1760adba424964050671d171c879dd976f7e8080a607c3e2ec001

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
